#!/bin/sh
# Fake wpa_cli(8) for the smoke test. Accepts and discards the -p/-i options
# the program passes, then answers the read-only commands it issues at startup.

while [ $# -gt 0 ]; do
    case "$1" in
        -p|-i)
            [ $# -ge 2 ] || break
            shift 2
            ;;
        *)
            break
            ;;
    esac
done

case "$*" in
    status)
        echo 'bssid=00:11:22:33:44:55'
        echo 'freq=2462'
        echo 'ssid=Lab WiFi'
        echo 'id=0'
        echo 'mode=station'
        echo 'pairwise_cipher=CCMP'
        echo 'group_cipher=CCMP'
        echo 'key_mgmt=WPA2-PSK'
        echo 'wpa_state=COMPLETED'
        echo 'ip_address=192.0.2.20'
        echo 'address=00:11:22:33:44:aa'
        ;;
    scan)
        echo OK
        ;;
    scan_results)
        printf 'bssid / frequency / signal level / flags / ssid\n'
        printf '00:11:22:33:44:55\t2462\t-47\t[WPA2-PSK-CCMP][ESS]\tLab WiFi\n'
        printf '00:11:22:33:44:77\t5180\t-60\t[WPA2-PSK+SAE-CCMP][ESS]\tModern Net\n'
        printf '00:11:22:33:44:66\t2437\t-72\t[ESS]\tCafe Guest\n'
        printf '00:11:22:33:44:88\t2412\t-80\t[WPA2-EAP-CCMP][ESS]\tCampus\n'
        printf '00:11:22:33:44:99\t2412\t-88\t[WPA2-PSK-CCMP][ESS]\t\n'
        ;;
    list_networks)
        printf 'network id / ssid / bssid / flags\n'
        printf '0\tLab WiFi\tany\t[CURRENT]\n'
        ;;
    *)
        echo "Unexpected fake wpa_cli call: $*" >&2
        exit 1
        ;;
esac
